name: Build push

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Install .NET Core 3.1 for testing
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.x

    # Install .NET 6 for building
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build and test
      run: |
        dotnet --info
        touch build_timing_log.txt
        ./build.sh
        ./processbuildtiminglog.sh
