name: Build and test PR (changed APIs only)

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    strategy:
      matrix:
        regex: ["'Google\\.Cloud\\.[A-L].*'", "'Google\\.Cloud\\.[M-Z].*'", "'!Google\\.Cloud'"]
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 100
        
    # Install .NET Core 3.1 for testing
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x

    # Install .NET 6 for building
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # The GitHub checkout action leaves the repo in a slightly awkward
    # state. This tidies it up.
    - name: Set up git branches
      run: |
        git checkout -b pr-head
        git checkout -b main ${{ github.event.pull_request.base.sha }}
        git checkout pr-head

    - name: Build and test
      run: |
        touch build_timing_log.txt
        ./build.sh --diff --regex ${{ matrix.regex }}
        ./processbuildtiminglog.sh
