name: Detect differences (PR only)

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:

  diff:
    # Don't run if a label has changed post-merge, or if a label other than "allow breaking changes"
    # has been added or removed.
    if: |
      (github.event.pull_request.merged == false) &&
      !(contains(fromJson('["labeled", "unlabeled"]'), github.event.action) && github.event.label.name != 'allow breaking changes')

    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 100

    # The GitHub checkout action leaves the repo in a slightly awkward
    # state. This tidies it up.
    - name: Set up git branches
      run: |
        git checkout -b pr-head
        git checkout -b master ${{ github.event.pull_request.base.sha }}
        git checkout pr-head

    - name: Detect PR changes
      env:
        ALLOW_BREAKING_CHANGES: ${{contains(github.event.pull_request.labels.*.name, 'allow breaking changes')}}
      run: |
        if [[ $ALLOW_BREAKING_CHANGES == "true" ]]
        then
          SCRIPT_OPTION=--allow-breaking-changes
        fi
        ./detect-pr-changes.sh $SCRIPT_OPTION
